/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-05-27 02:05:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Beans.Cart;
import Beans.CartItem;
import java.util.Map;
import Beans.Products;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("Beans.Cart");
    _jspx_imports_classes.add("Beans.CartItem");
    _jspx_imports_classes.add("Beans.Products");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Your Cart</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/tailwindcss@1.9.6/dist/tailwind.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100\">\r\n");
      out.write("    ");

        String message = (String) session.getAttribute("message");
        String error = (String) session.getAttribute("error");
        session.removeAttribute("message");
        session.removeAttribute("error");
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Success Toast -->\r\n");
      out.write("    ");
 if (message != null) { 
      out.write("\r\n");
      out.write("        <div id=\"success-toast\" class=\"bg-green-600 text-white p-4 rounded-lg shadow-lg mb-6 flex items-center space-x-4\">\r\n");
      out.write("            <i class=\"fas fa-check-circle text-xl\"></i>\r\n");
      out.write("            <span>");
      out.print( message );
      out.write("</span>\r\n");
      out.write("            <button onclick=\"closeToast('success-toast')\" class=\"ml-4 bg-transparent text-white font-bold py-2 px-4 border border-white rounded\">OK</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Error Toast -->\r\n");
      out.write("    ");
 if (error != null) { 
      out.write("\r\n");
      out.write("        <div id=\"error-toast\" class=\"bg-red-600 text-white p-4 rounded-lg shadow-lg mb-6 flex items-center space-x-4\">\r\n");
      out.write("            <i class=\"fas fa-exclamation-circle text-xl\"></i>\r\n");
      out.write("            <span>");
      out.print( error );
      out.write("</span>\r\n");
      out.write("            <button onclick=\"closeToast('error-toast')\" class=\"ml-4 bg-transparent text-white font-bold py-2 px-4 border border-white rounded\">OK</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function closeToast(id) {\r\n");
      out.write("            var toast = document.getElementById(id);\r\n");
      out.write("            if (toast) {\r\n");
      out.write("                toast.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        setTimeout(function() {\r\n");
      out.write("            var successToast = document.getElementById('success-toast');\r\n");
      out.write("            var errorToast = document.getElementById('error-toast');\r\n");
      out.write("            if (successToast) successToast.style.display = 'none';\r\n");
      out.write("            if (errorToast) errorToast.style.display = 'none';\r\n");
      out.write("        }, 5000);\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <header class=\"bg-white shadow-lg\">\r\n");
      out.write("        <div class=\"container mx-auto flex justify-between items-center py-4 px-6\">\r\n");
      out.write("            <div class=\"logo flex items-center\">\r\n");
      out.write("                <img alt=\"Jellycat logo\" class=\"mr-4\" height=\"50\" src=\"https://storage.googleapis.com/a1aa/image/FQHw3eMxpk2eakMv3O1MJ3DrSguzwJk8FAGfLnYFr6mlCFlnA.jpg\" width=\"50\">\r\n");
      out.write("                <span class=\"text-2xl font-bold text-blue-500\">JELLYCAT</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex items-center space-x-6\">\r\n");
      out.write("                <a href=\"ProductList\" class=\"text-gray-600 hover:text-blue-500\">Home</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container mx-auto py-8\">\r\n");
      out.write("        <h1 class=\"text-3xl font-bold mb-4\">GIỎ HÀNG</h1>\r\n");
      out.write("\r\n");
      out.write("        ");

            Beans.Cart cart = (Beans.Cart) session.getAttribute("cart");
            boolean hasInvalidItems = false;
            if (cart != null && !cart.isEmpty()) {
                for (Map.Entry<Integer, CartItem> entry : cart.getItems().entrySet()) {
                    CartItem item = entry.getValue();
                    if (item.getQuantity() < 1 || item.getQuantity() > 100 || !item.getProduct().getStatus()) {
                        hasInvalidItems = true;
                        break;
                    }
                }
                if (hasInvalidItems) {
        
      out.write("\r\n");
      out.write("                <div class=\"bg-yellow-600 text-white p-4 rounded-lg shadow-lg mb-6 flex items-center space-x-4\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-circle text-xl\"></i>\r\n");
      out.write("                    <span>Some items in your cart are invalid or out of stock and have been removed.</span>\r\n");
      out.write("                </div>\r\n");
      out.write("        ");

                }
        
      out.write("\r\n");
      out.write("        <table class=\"min-w-full bg-white border border-gray-300\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Image</th>\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Product Name</th>\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Price</th>\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Quantity</th>\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Total</th>\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Action</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");

                    for (Map.Entry<Integer, CartItem> entry : cart.getItems().entrySet()) {
                        Integer productId = entry.getKey();
                        CartItem item = entry.getValue();
                        Products product = item.getProduct();
                        if (item.getQuantity() >= 1 && item.getQuantity() <= 100 && product.getStatus()) {
                
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"py-2 px-4 border-b\">\r\n");
      out.write("                                    <img src=\"data:image/jpeg;base64,");
      out.print( java.util.Base64.getEncoder().encodeToString(product.getImage()) );
      out.write("\"\r\n");
      out.write("                                         alt=\"");
      out.print( product.getName() );
      out.write("\" class=\"w-20 h-20 object-cover\"/>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td class=\"py-2 px-4 border-b\">");
      out.print( product.getName() );
      out.write("</td>\r\n");
      out.write("                                <td class=\"py-2 px-4 border-b\">");
      out.print( product.getPrice() );
      out.write(" VND</td>\r\n");
      out.write("                                <td class=\"py-2 px-4 border-b\">\r\n");
      out.write("                                    <form action=\"CartServlet\" method=\"post\" class=\"inline\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"action\" value=\"edit\"/>\r\n");
      out.write("                                        <input type=\"hidden\" name=\"productId\" value=\"");
      out.print( productId );
      out.write("\"/>\r\n");
      out.write("                                        <input type=\"number\" name=\"quantity\" value=\"");
      out.print( item.getQuantity() );
      out.write("\" min=\"1\" max=\"100\" class=\"border border-gray-300 rounded px-2\"/>\r\n");
      out.write("                                        <input type=\"hidden\" name=\"csrfToken\" value=\"");
      out.print( session.getAttribute("csrfToken") );
      out.write("\" />\r\n");
      out.write("                                        <button type=\"submit\" class=\"ml-2 bg-blue-600 text-white rounded px-2 py-1\">Update</button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td class=\"py-2 px-4 border-b\">");
      out.print( item.getTotal() );
      out.write(" VND</td>\r\n");
      out.write("                                <td class=\"py-2 px-4 border-b\">\r\n");
      out.write("                                    <form action=\"CartServlet\" method=\"post\" class=\"inline\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"action\" value=\"remove\"/>\r\n");
      out.write("                                        <input type=\"hidden\" name=\"productId\" value=\"");
      out.print( productId );
      out.write("\"/>\r\n");
      out.write("                                        <input type=\"hidden\" name=\"csrfToken\" value=\"");
      out.print( session.getAttribute("csrfToken") );
      out.write("\" />\r\n");
      out.write("                                        <button type=\"submit\" class=\"bg-red-600 text-white rounded px-2 py-1\">Remove</button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                ");

                        }
                    }
                
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mt-4\">\r\n");
      out.write("            <h2 class=\"text-xl font-bold\">Total Amount: ");
      out.print( cart.getTotalPrice() );
      out.write(" VND</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mt-4\">\r\n");
      out.write("            <a href=\"ProductList\" class=\"bg-green-600 text-white rounded px-4 py-2\">TIẾP TỤC MUA SẮM</a>\r\n");
      out.write("            <a href=\"checkout.jsp\" class=\"bg-blue-600 text-white rounded px-4 py-2 ml-2\">ĐẶT HÀNG</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

            } else {
        
      out.write("\r\n");
      out.write("        <p class=\"text-gray-500\">GIỎ HÀNG TRỐNG.</p>\r\n");
      out.write("        <a href=\"ProductList\" class=\"bg-green-600 text-white rounded px-4 py-2\">TIẾP TỤC MUA SẮM</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
