/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-05-27 02:05:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <title>Jellycat</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"font-roboto bg-gray-100\">\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"border-b bg-white shadow-sm\">\r\n");
      out.write("        <div class=\"container mx-auto flex justify-between items-center py-4 px-6\">\r\n");
      out.write("            <!-- Logo -->\r\n");
      out.write("            <div class=\"logo flex items-center\">\r\n");
      out.write("                <img alt=\"Jellycat logo\" class=\"mr-4\" height=\"50\" src=\"https://storage.googleapis.com/a1aa/image/FQHw3eMxpk2eakMv3O1MJ3DrSguzwJk8FAGfLnYFr6mlCFlnA.jpg\" width=\"50\">\r\n");
      out.write("                <span class=\"text-2xl font-bold text-blue-500\">JELLYCAT</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Icons -->\r\n");
      out.write("            <div class=\"flex items-center space-x-6\">\r\n");
      out.write("                ");

                    // Kiểm tra xem người dùng đã đăng nhập hay chưa
                    String profileLink;
                    if (session.getAttribute("user") != null) {
                        // Nếu đã đăng nhập, dẫn đến profile.jsp
                        profileLink = "profile.jsp";
                    } else {
                        // Nếu chưa đăng nhập, dẫn đến signinup.jsp
                        profileLink = "signinup.jsp";
                    }
                
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print( profileLink );
      out.write("\">\r\n");
      out.write("                    <i class=\"fas fa-user text-gray-600 text-lg cursor-pointer\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <i class=\"fas fa-heart text-gray-600 text-lg cursor-pointer\"></i>\r\n");
      out.write("                <a href=\"cart.jsp\"> \r\n");
      out.write("                    <i class=\"fas fa-shopping-cart text-gray-600 text-lg cursor-pointer\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"bg-gray-100\">\r\n");
      out.write("        <div class=\"container mx-auto flex items-center justify-between py-3\">\r\n");
      out.write("            <!-- Các mục còn lại ở chính giữa -->\r\n");
      out.write("             <div class=\"flex justify-center space-x-8\">\r\n");
      out.write("                <a class=\"text-gray-600 text-sm font-bold hover:text-black\" href=\"about.jsp\">GIỚI THIỆU</a>\r\n");
      out.write("                <a class=\"text-gray-600 text-sm font-bold hover:text-black\" href=\"ProductList\">SẢN PHẨM</a>\r\n");
      out.write("                <a class=\"text-gray-600 text-sm font-bold hover:text-black\" href=\"CustomerOrder\">ĐƠN HÀNG</a>\r\n");
      out.write("                <a class=\"text-gray-600 text-sm font-bold hover:text-black\" href=\"contact.jsp\">LIÊN HỆ</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Contact Section -->\r\n");
      out.write("    <div class=\"container mx-auto p-6\">\r\n");
      out.write("		<div class=\"bg-white shadow-md rounded-lg p-6\">\r\n");
      out.write("    		<h1 class=\"text-3xl font-bold mb-6 text-center text-blue-500\">\r\n");
      out.write("     			Liên Hệ\r\n");
      out.write("    		</h1>\r\n");
      out.write("    	<div class=\"flex flex-col md:flex-row items-center mb-6\">\r\n");
      out.write("     		<div class=\"md:w-1/2 mb-6 md:mb-0\">\r\n");
      out.write("      			<img alt=\"A cute cartoon teddy bear holding a heart\" class=\"rounded-lg shadow-md\" height=\"400\" src=\"https://storage.googleapis.com/a1aa/image/2RHzJLcVQt6LGZIYkfWubWbLFRPbeaQRe1kZOH3zaR5OYIwnA.jpg\" width=\"400\"/>\r\n");
      out.write("     		</div>\r\n");
      out.write("		<div class=\"md:w-1/2 md:pl-6\">\r\n");
      out.write("      		<div class=\"mb-6 flex items-center\">\r\n");
      out.write("		    <h2 class=\"text-xl font-semibold text-gray-800 mr-4\">\r\n");
      out.write("		        Tên Shop\r\n");
      out.write("		    </h2>\r\n");
      out.write("		    <p class=\"text-2xl font-bold text-blue-500\">\r\n");
      out.write("		    	JELLYCAT\r\n");
      out.write("		    </p>\r\n");
      out.write("			</div>\r\n");
      out.write("		<div class=\"mb-6\">\r\n");
      out.write("       		<h2 class=\"text-xl font-semibold text-gray-800\">\r\n");
      out.write("        		Số Điện Thoại\r\n");
      out.write("       		</h2>\r\n");
      out.write("       	<p class=\"text-gray-700\">\r\n");
      out.write("        	<i class=\"fas fa-phone-alt text-blue-500\">\r\n");
      out.write("        	</i>\r\n");
      out.write("        		0386215152\r\n");
      out.write("       	</p>\r\n");
      out.write("      	</div>\r\n");
      out.write("      	<div class=\"mb-6\">\r\n");
      out.write("       		<h2 class=\"text-xl font-semibold text-gray-800\">\r\n");
      out.write("        		Email\r\n");
      out.write("       		</h2>\r\n");
      out.write("       		<p class=\"text-gray-700\">\r\n");
      out.write("        	<i class=\"fas fa-envelope text-blue-500\">\r\n");
      out.write("        	</i>\r\n");
      out.write("        		HongSang@gmail.com\r\n");
      out.write("       		</p>\r\n");
      out.write("      	</div>\r\n");
      out.write("      	<div class=\"mb-6\">\r\n");
      out.write("       		<h2 class=\"text-xl font-semibold text-gray-800\">\r\n");
      out.write("        		Địa Chỉ\r\n");
      out.write("       		</h2>\r\n");
      out.write("       		<p class=\"text-gray-700\">\r\n");
      out.write("        	<i class=\"fas fa-map-marker-alt text-blue-500\">\r\n");
      out.write("        	</i>\r\n");
      out.write("        		123 Đường Thành Đạt, Quận 9, TP. Hồ Chí Minh, Việt Nam\r\n");
      out.write("       		</p>\r\n");
      out.write("      	</div>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script>\r\n");
      out.write("   function toggleDropdown() {\r\n");
      out.write("            var dropdown = document.getElementById('dropdown');\r\n");
      out.write("            dropdown.classList.toggle('hidden');\r\n");
      out.write("        }\r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
