/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-05-26 14:45:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import Beans.Orders;
import Beans.Users;
import Utils.DBOrder;

public final class customerOrders_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/slideHeader.jsp", Long.valueOf(1748268469155L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("Utils.DBOrder");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Beans.Users");
    _jspx_imports_classes.add("Beans.Orders");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    HttpSession sessionCheck = request.getSession(false);
    if (sessionCheck == null || sessionCheck.getAttribute("user") == null) {
        response.sendRedirect("signinup.jsp?status=login_required");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"csrf-token\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.csrfToken}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    <title>Jellycat</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/csrf-protection.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Roboto', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100\">\r\n");
      out.write("    ");

        String message = (String) session.getAttribute("message");
        String error = (String) session.getAttribute("error");
        session.removeAttribute("message");
        session.removeAttribute("error");
    
      out.write("\r\n");
      out.write("    <!-- Thông báo thành công -->\r\n");
      out.write("    ");
 if (message != null) { 
      out.write("\r\n");
      out.write("    <div id=\"success-toast\" class=\"bg-green-600 text-white p-4 rounded-lg shadow-lg mb-6 flex items-center space-x-4 max-w-3xl mx-auto\">\r\n");
      out.write("        <i class=\"fas fa-check-circle text-xl\"></i>\r\n");
      out.write("        <span>");
      out.print( message );
      out.write("</span>\r\n");
      out.write("        <button onclick=\"closeToast('success-toast')\" class=\"ml-4 bg-transparent text-white font-bold py-2 px-4 border border-white rounded\">OK</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    <!-- Thông báo lỗi -->\r\n");
      out.write("    ");
 if (error != null) { 
      out.write("\r\n");
      out.write("    <div id=\"error-toast\" class=\"bg-red-600 text-white p-4 rounded-lg shadow-lg mb-6 flex items-center space-x-4 max-w-3xl mx-auto\">\r\n");
      out.write("        <i class=\"fas fa-exclamation-circle text-xl\"></i>\r\n");
      out.write("        <span>");
      out.print( error );
      out.write("</span>\r\n");
      out.write("        <button onclick=\"closeToast('error-toast')\" class=\"ml-4 bg-transparent text-white font-bold py-2 px-4 border border-white rounded\">OK</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function closeToast(id) {\r\n");
      out.write("            const toast = document.getElementById(id);\r\n");
      out.write("            if (toast) {\r\n");
      out.write("                toast.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        setTimeout(() => {\r\n");
      out.write("            const successToast = document.getElementById('success-toast');\r\n");
      out.write("            const errorToast = document.getElementById('error-toast');\r\n");
      out.write("            if (successToast) successToast.style.display = 'none';\r\n");
      out.write("            if (errorToast) errorToast.style.display = 'none';\r\n");
      out.write("        }, 5000);\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- Slideshow Section -->\r\n");
      out.write("    <div class=\"slideshow-container\">\r\n");
      out.write("        ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <title>Slideshow Example</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        #slideshow {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            transition: transform 0.5s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"font-roboto\">\r\n");
      out.write("<!-- Slideshow Section -->\r\n");
      out.write("<div class=\"relative w-full max-w-6xl mx-auto mt-12 overflow-hidden\">\r\n");
      out.write("    <!-- Slides -->\r\n");
      out.write("    <div id=\"slideshow\" class=\"relative flex transition-transform duration-700 ease-in-out w-full\">\r\n");
      out.write("        <!-- Slide 1 -->\r\n");
      out.write("        <div class=\"flex-shrink-0 w-full\">\r\n");
      out.write("            <img class=\"w-full h-80 object-cover\"\r\n");
      out.write("                 src=\"https://bloomingdales.ae/on/demandware.static/-/Library-Sites-BloomingDalesSharedLibrary/default/dwc73befc3/FINAL-IMAGES-24/BRAND-HEADERS/mobile-brand/WK50_24-BLM-JellyCat-PLP-Banner-MB.jpg\"\r\n");
      out.write("                 alt=\"A colorful display of various Jellycat plush toys arranged in a playful manner\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Slide 2 -->\r\n");
      out.write("        <div class=\"flex-shrink-0 w-full\">\r\n");
      out.write("            <img class=\"w-full h-80 object-cover\"\r\n");
      out.write("                 src=\"https://mystyle.vn/wp-content/uploads/2023/10/easter-jellycat-1370x900_jpg.jpg\"\r\n");
      out.write("                 alt=\"A cozy room setting with Jellycat plush toys placed on a shelf and a bed\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Slide 3 -->\r\n");
      out.write("        <div class=\"flex-shrink-0 w-full\">\r\n");
      out.write("            <img class=\"w-full h-80 object-cover\"\r\n");
      out.write("                 src=\"https://m.media-amazon.com/images/I/51WlI+cS1mL._AC_SY355_.jpg\"\r\n");
      out.write("                 alt=\"A group of children playing with Jellycat plush toys in a park\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navigation Dots -->\r\n");
      out.write("    <div class=\"absolute bottom-4 left-1/2 transform -translate-x-1/2 flex space-x-2\">\r\n");
      out.write("        <button onclick=\"navigateSlide(0)\" class=\"dot w-3 h-3 rounded-full bg-gray-300\"></button>\r\n");
      out.write("        <button onclick=\"navigateSlide(1)\" class=\"dot w-3 h-3 rounded-full bg-gray-300\"></button>\r\n");
      out.write("        <button onclick=\"navigateSlide(2)\" class=\"dot w-3 h-3 rounded-full bg-gray-300\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navigation Buttons -->\r\n");
      out.write("    <button id=\"prev\" class=\"absolute left-0 top-1/2 transform -translate-y-1/2 bg-gray-800 text-white px-4 py-2 rounded-l-md hover:bg-gray-600\">\r\n");
      out.write("        &#8249; <!-- Left Arrow -->\r\n");
      out.write("    </button>\r\n");
      out.write("    <button id=\"next\" class=\"absolute right-0 top-1/2 transform -translate-y-1/2 bg-gray-800 text-white px-4 py-2 rounded-r-md hover:bg-gray-600\">\r\n");
      out.write("        &#8250; <!-- Right Arrow -->\r\n");
      out.write("    </button>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Link external JavaScript -->\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"border-b\">\r\n");
      out.write("        <div class=\"container mx-auto flex justify-between items-center py-4 px-6\">\r\n");
      out.write("            <div class=\"logo flex items-center\">\r\n");
      out.write("                <img alt=\"Jellycat logo\" class=\"mr-4\" height=\"50\" src=\"https://storage.googleapis.com/a1aa/image/FQHw3eMxpk2eakMv3O1MJ3DrSguzwJk8FAGfLnYFr6mlCFlnA.jpg\" width=\"50\">\r\n");
      out.write("                <span class=\"text-2xl font-bold text-blue-500\">JELLYCAT</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex items-center space-x-6\">\r\n");
      out.write("                ");

                    String profileLink = sessionCheck.getAttribute("user") != null ? "profile.jsp" : "signinup.jsp";
                
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print( profileLink );
      out.write("\">\r\n");
      out.write("                    <i class=\"fas fa-user text-gray-600 text-lg cursor-pointer\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <i class=\"fas fa-heart text-gray-600 text-lg cursor-pointer\"></i>\r\n");
      out.write("                <a href=\"cart.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-shopping-cart text-gray-600 text-lg cursor-pointer\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"bg-gray-100\">\r\n");
      out.write("        <div class=\"container mx-auto flex items-center justify-center py-3\">\r\n");
      out.write("            <div class=\"flex space-x-8\">\r\n");
      out.write("                <a class=\"text-gray-600 text-sm font-bold hover:text-black\" href=\"about.jsp\">GIỚI THIỆU</a>\r\n");
      out.write("                <a class=\"text-gray-600 text-sm font-bold hover:text-black\" href=\"ProductList\">SẢN PHẨM</a>\r\n");
      out.write("                <a class=\"text-gray-600 text-sm font-bold hover:text-black\" href=\"CustomerOrder\">ĐƠN HÀNG</a>\r\n");
      out.write("                <a class=\"text-gray-600 text-sm font-bold hover:text-black\" href=\"contact.jsp\">LIÊN HỆ</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Orders Section -->\r\n");
      out.write("    <div class=\"max-w-7xl mx-auto px-4 py-6\" id=\"main-content\">\r\n");
      out.write("        <h1 class=\"text-3xl font-bold mb-6\">Danh sách đơn hàng</h1>\r\n");
      out.write("        <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\" id=\"order-list\">\r\n");
      out.write("            ");

                List<Orders> ordersList = (List<Orders>) request.getAttribute("ordersList");
                if (ordersList != null && !ordersList.isEmpty()) {
                    for (Orders order : ordersList) {
            
      out.write("\r\n");
      out.write("            <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("                <h2 class=\"text-xl font-bold mb-2\">Mã đơn hàng: ");
      out.print( order.getOrderId() );
      out.write("</h2>\r\n");
      out.write("                <p class=\"text-gray-700 mb-4\">Tổng tiền: ");
      out.print( order.getTotalAmount() );
      out.write("</p>\r\n");
      out.write("                <p class=\"text-gray-700 mb-4\">Trạng thái thanh toán: ");
      out.print( order.isPaymentStatus() ? "Đã thanh toán" : "Chưa thanh toán" );
      out.write("</p>\r\n");
      out.write("                <p class=\"text-gray-700 mb-4\">Trạng thái giao hàng: ");
      out.print( order.getDeliveryStatus() );
      out.write("</p>\r\n");
      out.write("                <p class=\"text-gray-700 mb-4\">Ngày tạo: ");
      out.print( order.getCreatedAt() );
      out.write("</p>\r\n");
      out.write("                <p class=\"text-gray-700 mb-4\">Ngày cập nhật: ");
      out.print( order.getUpdatedAt() );
      out.write("</p>\r\n");
      out.write("                <a href=\"CustomerOrder?order_id=");
      out.print( order.getOrderId() );
      out.write("\" class=\"bg-blue-500 text-white px-3 py-1 rounded\">Chi tiết</a>\r\n");
      out.write("                ");
 if (!order.isPaymentStatus()) { 
      out.write("\r\n");
      out.write("                <form action=\"CustomerOrder\" method=\"post\" class=\"mt-4\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"orderId\" value=\"");
      out.print( order.getOrderId() );
      out.write("\">\r\n");
      out.write("                    <button type=\"submit\" name=\"action\" value=\"received\" class=\"bg-green-500 text-white px-4 py-2 rounded\">Đã nhận được hàng</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                    }
                } else {
            
      out.write("\r\n");
      out.write("            <p class=\"text-center text-gray-500\">Không có đơn hàng nào.</p>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
